
package app.Prismas;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import mx.tecnm.itl.prismas.Cilindro;
import mx.tecnm.itl.prismas.PrismaRectangular;
import mx.tecnm.itl.prismas.PrismaTriangular;
        
/**
 *
 * @author adria
 */
public class PrismasFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrismasFrame
     */
    public PrismasFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabIcon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabAreaBaseCilindro = new javax.swing.JLabel();
        jLabAreaLateralCilindro = new javax.swing.JLabel();
        jLabAreaTotalCilindro = new javax.swing.JLabel();
        jLabVolumenCilindro = new javax.swing.JLabel();
        jButCalcularCilindro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextAlturaCilindro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextRadio = new javax.swing.JTextField();
        jLabLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabAreaLateralTriangular = new javax.swing.JLabel();
        jLabAreaBaseTriangular = new javax.swing.JLabel();
        jLabAreaTotalTriangular = new javax.swing.JLabel();
        jLabVolumenTriangular = new javax.swing.JLabel();
        jButCalcularTriangular = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextAlturaTriangular = new javax.swing.JTextField();
        jTextBaseTriangular = new javax.swing.JTextField();
        jTextAlturaBaseTriangular = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabAreaLateralRectangular = new javax.swing.JLabel();
        jLabAreaBaseRectangular = new javax.swing.JLabel();
        jLabAreaTotalRectangular = new javax.swing.JLabel();
        jLabVolumenRectangular = new javax.swing.JLabel();
        jButCalcularRectangular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextAlturaRectangular = new javax.swing.JTextField();
        jTextBaseRectangular = new javax.swing.JTextField();
        jTextAnchoRectangular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButRegresar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 2, 16))); // NOI18N

        jLabel24.setText("Área base");

        jLabel25.setText("Área lateral");

        jLabel26.setText("Área total");

        jLabel27.setText("Volumen");

        jLabAreaBaseCilindro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabAreaBaseCilindro.setForeground(new java.awt.Color(255, 0, 0));
        jLabAreaBaseCilindro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabAreaBaseCilindro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabAreaLateralCilindro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabAreaLateralCilindro.setForeground(new java.awt.Color(255, 0, 0));
        jLabAreaLateralCilindro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabAreaLateralCilindro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabAreaTotalCilindro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabAreaTotalCilindro.setForeground(new java.awt.Color(255, 0, 0));
        jLabAreaTotalCilindro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabAreaTotalCilindro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabVolumenCilindro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabVolumenCilindro.setForeground(new java.awt.Color(255, 0, 0));
        jLabVolumenCilindro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabVolumenCilindro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabAreaLateralCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabAreaBaseCilindro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabAreaTotalCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabVolumenCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabAreaBaseCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabAreaLateralCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel25)))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabAreaTotalCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabVolumenCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButCalcularCilindro.setText("Calcular");
        jButCalcularCilindro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularCilindroActionPerformed(evt);
            }
        });

        jLabel3.setText("h:");

        jLabel4.setText("r:");

        jLabLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cilindro.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextAlturaCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabIcon)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jButCalcularCilindro)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButCalcularCilindro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextAlturaCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabLogo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("Cilindro", jPanel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Prisma_Triangular.jpg"))); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 2, 16))); // NOI18N

        jLabel16.setText("Área base");

        jLabel17.setText("Área lateral");

        jLabel18.setText("Área total");

        jLabel19.setText("Volumen");

        jLabAreaLateralTriangular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabAreaLateralTriangular.setForeground(new java.awt.Color(255, 0, 0));
        jLabAreaLateralTriangular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabAreaLateralTriangular.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabAreaBaseTriangular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabAreaBaseTriangular.setForeground(new java.awt.Color(255, 0, 0));
        jLabAreaBaseTriangular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabAreaBaseTriangular.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabAreaTotalTriangular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabAreaTotalTriangular.setForeground(new java.awt.Color(255, 0, 0));
        jLabAreaTotalTriangular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabAreaTotalTriangular.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabVolumenTriangular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabVolumenTriangular.setForeground(new java.awt.Color(255, 0, 0));
        jLabVolumenTriangular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabVolumenTriangular.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabAreaLateralTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabAreaBaseTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabAreaTotalTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabVolumenTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabAreaBaseTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabAreaLateralTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabAreaTotalTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabVolumenTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        jButCalcularTriangular.setText("Calcular");
        jButCalcularTriangular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularTriangularActionPerformed(evt);
            }
        });

        jLabel8.setText("h:");

        jLabel11.setText("b:");

        jLabel12.setText("a:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextAlturaTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextAlturaBaseTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButCalcularTriangular)
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextBaseTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextBaseTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButCalcularTriangular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAlturaTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAlturaBaseTriangular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prisma Triangular", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 2, 16))); // NOI18N

        jLabel20.setText("Área base");

        jLabel21.setText("Área lateral");

        jLabel22.setText("Área total");

        jLabel23.setText("Volumen");

        jLabAreaLateralRectangular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabAreaLateralRectangular.setForeground(new java.awt.Color(255, 0, 0));
        jLabAreaLateralRectangular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabAreaLateralRectangular.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabAreaBaseRectangular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabAreaBaseRectangular.setForeground(new java.awt.Color(255, 0, 0));
        jLabAreaBaseRectangular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabAreaBaseRectangular.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabAreaTotalRectangular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabAreaTotalRectangular.setForeground(new java.awt.Color(255, 0, 0));
        jLabAreaTotalRectangular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabAreaTotalRectangular.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabVolumenRectangular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabVolumenRectangular.setForeground(new java.awt.Color(255, 0, 0));
        jLabVolumenRectangular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabVolumenRectangular.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabAreaLateralRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabAreaBaseRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabAreaTotalRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabVolumenRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabAreaBaseRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabAreaLateralRectangular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabAreaTotalRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabVolumenRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(29, 29, 29))
        );

        jButCalcularRectangular.setText("Calcular");
        jButCalcularRectangular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularRectangularActionPerformed(evt);
            }
        });

        jLabel5.setText("h:");

        jLabel6.setText("a:");

        jLabel7.setText("b:");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Prisma_Rectangular.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextBaseRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextAlturaRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextAnchoRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButCalcularRectangular)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButCalcularRectangular)
                                        .addGap(107, 107, 107))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextBaseRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAlturaRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAnchoRectangular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Prisma Rectangular", jPanel3);

        jButRegresar.setText("Regresar");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Limpiar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButRegresar)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        dispose();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        this.jLabAreaBaseCilindro.setText     ( "" ) ;
        this.jLabAreaLateralCilindro.setText  ( "" );
        this.jLabAreaTotalCilindro.setText    ( "" );
        this.jLabVolumenCilindro.setText      ( "" );
        this.jTextAlturaCilindro.setText      ( "" );
        this.jTextRadio.setText               ( "" );
        this.jTextAlturaCilindro.requestFocus();

        this.jLabAreaBaseRectangular.setText     ( "" ) ;
        this.jLabAreaLateralRectangular.setText  ( "" );
        this.jLabAreaTotalRectangular.setText    ( "" );
        this.jLabVolumenRectangular.setText      ( "" );
        this.jTextAlturaRectangular.setText      ( "" );
        this.jTextAnchoRectangular.setText       ( "" );
        this.jTextBaseRectangular.setText        ( "" );
        this.jTextAlturaRectangular.requestFocus();

        this.jLabAreaBaseTriangular.setText     ( "" ) ;
        this.jLabAreaLateralTriangular.setText  ( "" );
        this.jLabAreaTotalTriangular.setText    ( "" );
        this.jLabVolumenTriangular.setText      ( "" );
        this.jTextAlturaTriangular.setText      ( "" );
        this.jTextAlturaBaseTriangular.setText  ( "" );
        this.jTextBaseTriangular.setText        ( "" );
        this.jTextAlturaRectangular.requestFocus();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButCalcularRectangularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularRectangularActionPerformed

        DecimalFormat df = new DecimalFormat ( "#.####" );

        double alturaPrisma = 0;
        double ancho        = 0;
        double largo        = 0;

        try {

            alturaPrisma = Double.parseDouble ( this.jTextAlturaRectangular.getText () );
            ancho = Double.parseDouble        ( this.jTextAnchoRectangular.getText () );
            largo = Double.parseDouble        ( this.jTextBaseRectangular.getText () );

        } catch ( NumberFormatException ex ) {
            JOptionPane.showMessageDialog ( this ,
                "El valor ingresado no es valido" ,
                "Error #001" ,
                JOptionPane.ERROR_MESSAGE
            );
            this.jTextAlturaRectangular.requestFocus ();
            this.jTextAnchoRectangular.requestFocus ();
            this.jTextBaseRectangular.requestFocus();
            return;
        }

        PrismaRectangular Rectangulito = new PrismaRectangular ( largo, ancho, alturaPrisma );
        this.jLabAreaBaseRectangular.setText     (  (Rectangulito.areaBase ()  + "" ) );
        this.jLabAreaLateralRectangular.setText  (  (Rectangulito.areaLateral()+ "" ) );
        this.jLabAreaTotalRectangular.setText    (  (Rectangulito.areaTotal()  + "" ) );
        this.jLabVolumenRectangular.setText      (  (Rectangulito.Volumen()    + "" ) );

    }//GEN-LAST:event_jButCalcularRectangularActionPerformed

    private void jButCalcularCilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularCilindroActionPerformed

        DecimalFormat df = new DecimalFormat ( "#.####" );

        double radio  = 0;
        double altura = 0;

        try {

            radio = Double.parseDouble  ( this.jTextRadio.getText () );
            altura = Double.parseDouble ( this.jTextAlturaCilindro.getText () );

        } catch ( NumberFormatException ex ) {
            JOptionPane.showMessageDialog ( this ,
                "El valor ingresado no es valido" ,
                "Error #001" ,
                JOptionPane.ERROR_MESSAGE
            );
            this.jTextRadio.requestFocus ();
            this.jTextAlturaCilindro.requestFocus ();
            return;
        }

        Cilindro cilindrito = new Cilindro ( radio, altura );
        this.jLabAreaBaseCilindro.setText     (  (cilindrito.areaBase ()  + "" ) );
        this.jLabAreaLateralCilindro.setText  (  (cilindrito.areaLateral()+ "" ) );
        this.jLabAreaTotalCilindro.setText    (  (cilindrito.areaTotal()  + "" ) );
        this.jLabVolumenCilindro.setText      (  (cilindrito.Volumen()    + "" ) );

    }//GEN-LAST:event_jButCalcularCilindroActionPerformed

    private void jButCalcularTriangularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularTriangularActionPerformed

        DecimalFormat df = new DecimalFormat ( "#.####" );

        double base         = 0;
        double alturaBase   = 0;
        double alturaPrisma = 0;

        try {

            base = Double.parseDouble         ( this.jTextBaseTriangular.getText () );
            alturaBase = Double.parseDouble   ( this.jTextAlturaBaseTriangular.getText () );
            alturaPrisma = Double.parseDouble ( this.jTextAlturaTriangular.getText () );

        } catch ( NumberFormatException ex ) {
            JOptionPane.showMessageDialog ( this ,
                "El valor ingresado no es valido" ,
                "Error  #001 ",
                JOptionPane.ERROR_MESSAGE
            );
            this.jTextBaseTriangular.requestFocus ();
            this.jTextAlturaBaseTriangular.requestFocus ();
            this.jTextAlturaTriangular.requestFocus();
            return;
        }

        PrismaTriangular Triangulito = new PrismaTriangular ( base, alturaBase, alturaPrisma );
        this.jLabAreaBaseTriangular.setText     (  ( Triangulito.areaBase ()  + "" ) );
        this.jLabAreaLateralTriangular.setText  (  ( Triangulito.areaLateral()+ "" ) );
        this.jLabAreaTotalTriangular.setText    (  ( Triangulito.areaTotal()  + "" ) );
        this.jLabVolumenTriangular.setText      (  ( Triangulito.Volumen()    + "" ) );

    }//GEN-LAST:event_jButCalcularTriangularActionPerformed

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        dispose ();
    }//GEN-LAST:event_jButRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrismasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrismasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrismasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrismasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrismasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButCalcularCilindro;
    private javax.swing.JButton jButCalcularRectangular;
    private javax.swing.JButton jButCalcularTriangular;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JLabel jLabAreaBaseCilindro;
    private javax.swing.JLabel jLabAreaBaseRectangular;
    private javax.swing.JLabel jLabAreaBaseTriangular;
    private javax.swing.JLabel jLabAreaLateralCilindro;
    private javax.swing.JLabel jLabAreaLateralRectangular;
    private javax.swing.JLabel jLabAreaLateralTriangular;
    private javax.swing.JLabel jLabAreaTotalCilindro;
    private javax.swing.JLabel jLabAreaTotalRectangular;
    private javax.swing.JLabel jLabAreaTotalTriangular;
    private javax.swing.JLabel jLabIcon;
    private javax.swing.JLabel jLabLogo;
    private javax.swing.JLabel jLabVolumenCilindro;
    private javax.swing.JLabel jLabVolumenRectangular;
    private javax.swing.JLabel jLabVolumenTriangular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextAlturaBaseTriangular;
    private javax.swing.JTextField jTextAlturaCilindro;
    private javax.swing.JTextField jTextAlturaRectangular;
    private javax.swing.JTextField jTextAlturaTriangular;
    private javax.swing.JTextField jTextAnchoRectangular;
    private javax.swing.JTextField jTextBaseRectangular;
    private javax.swing.JTextField jTextBaseTriangular;
    private javax.swing.JTextField jTextRadio;
    // End of variables declaration//GEN-END:variables
}
