/* -----------------------------------------------------------------------------
                       INSTITUTO TECNOLOGICO DE LA LAGUNA
                     INGENIERIA EN SISTEMAS COMPUTACIONALES
                       TOPICOS AVANZADOS DE PROGRAMACION "B"

                   SEMESTRE: ENE-JUN/2020   HORA: 10-11 HRS

                       Bean PelotasRebotando


  Archivo     : PelotaRebotandoBean.java
  Autor       : jesus Adrian Lopez Luevanos 18131253
  Fecha       : 14/01/2021
  Compilador  : Java j2SE V1.8.0
  Descripción : Panel que implementa una clase y forma un bean, con su funcion 
                de simulacion de rebote de una peloa dentro de un jPanel.

--------------------------------------------------------------------------------
Ultima Modificacion: 
Fecha: 15/01/2021
Modifico: Jesus Adrian Lopez Luevanos
Motivo: Añadir prologo
*/

package Pelotas;

public class PelotaRebotandoBean extends javax.swing.JPanel {
//------------------------------------------------------------------------------    
    Pelota pelota;

    public PelotaRebotandoBean() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlMarcoPelota = new javax.swing.JPanel();
        jButIniciar = new javax.swing.JButton();
        jButDetener = new javax.swing.JButton();

        jPnlMarcoPelota.setBackground(new java.awt.Color(255, 255, 255));
        jPnlMarcoPelota.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPnlMarcoPelotaLayout = new javax.swing.GroupLayout(jPnlMarcoPelota);
        jPnlMarcoPelota.setLayout(jPnlMarcoPelotaLayout);
        jPnlMarcoPelotaLayout.setHorizontalGroup(
            jPnlMarcoPelotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPnlMarcoPelotaLayout.setVerticalGroup(
            jPnlMarcoPelotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jButIniciar.setText("Iniciar");
        jButIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButIniciarActionPerformed(evt);
            }
        });

        jButDetener.setText("Detener");
        jButDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDetenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPnlMarcoPelota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButDetener)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlMarcoPelota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButIniciar)
                    .addComponent(jButDetener))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
//------------------------------------------------------------------------------
    //Boton Iniciar
    private void jButIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButIniciarActionPerformed
       pelota = new Pelota( jPnlMarcoPelota );
       pelota.start();
        
    }//GEN-LAST:event_jButIniciarActionPerformed

//------------------------------------------------------------------------------
    //Boton Detener
    private void jButDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDetenerActionPerformed
        pelota.seguirRebotando = false;
    }//GEN-LAST:event_jButDetenerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButDetener;
    private javax.swing.JButton jButIniciar;
    private javax.swing.JPanel jPnlMarcoPelota;
    // End of variables declaration//GEN-END:variables
}
