
package mx.tecnm.beans;

import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author adria
 */
public class DatosCilindroDialog extends javax.swing.JDialog {

    private jCilindro parent;
    /**
     * Creates new form DatosCilindroDialog
     */
    public DatosCilindroDialog(jCilindro parent, boolean modal) {
        super(new Frame (), modal);
        initComponents();
        
        //Conservamos la referencia a la vista
        this.parent = parent;
        
      //Iniciamos los valorea JtextField a la vista
      jTextRadio.setText  ( "" + parent.getRadio  () );
      jTextAltura.setText ( "" + parent.getAltura () );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextRadio = new javax.swing.JTextField();
        jTextAltura = new javax.swing.JTextField();
        jButAceptar = new javax.swing.JButton();
        jButCancelar = new javax.swing.JButton();

        setTitle("Datos del Cilindro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Radio ( r ):");

        jLabel2.setText("Altura ( h ):");

        jTextRadio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextAltura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButAceptar.setText("Aceptar");
        jButAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAceptarActionPerformed(evt);
            }
        });

        jButCancelar.setText("Cancelar");
        jButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextAltura)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCancelar)
                    .addComponent(jButAceptar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelarActionPerformed
        this.setVisible ( false );
    }//GEN-LAST:event_jButCancelarActionPerformed

    private void jButAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAceptarActionPerformed
       double Radio, Altura;
       
       //Convertimos a valor numerio el radio
       try{
       Radio = Double.parseDouble ( jTextRadio.getText () );
       }catch ( NumberFormatException ex ){
           JOptionPane.showMessageDialog(
                   this,
                   "Debe de capturar un valor numerico para el radio",
                   "Error",
                   JOptionPane.ERROR_MESSAGE);
           jTextRadio.requestFocus();
           return;
       }
       
       //Convertimos a valor numerio la altura
       try{
       Altura = Double.parseDouble(jTextAltura.getText () );
       } catch ( NumberFormatException ex ){
           JOptionPane.showMessageDialog(
                   this,
                   "Debe de capturar un valor numerico para la Altura",
                   "Error",
                   JOptionPane.ERROR_MESSAGE);
           jTextAltura.requestFocus();
           return;
       }
       
       DatosModificadosEvent ev = new DatosModificadosEvent (
            parent.getRadio(), 
            parent.getAltura(), Radio, Altura
       );
        
       parent.setRadio  ( Radio  );
       parent.setAltura ( Altura );
       setVisible       ( false  );
       
       parent.fireDatosModificadosEvent( ev );
    }//GEN-LAST:event_jButAceptarActionPerformed

        
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      //Iniciamos los valorea JtextField a la vista
//      jTextRadio.setText  ( "" + parent.getRadio  () );
//      jTextAltura.setText ( "" + parent.getAltura () );
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      jTextRadio.setText  ( "" + parent.getRadio  () );
      jTextAltura.setText ( "" + parent.getAltura () );
    }//GEN-LAST:event_formWindowActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAceptar;
    private javax.swing.JButton jButCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextAltura;
    private javax.swing.JTextField jTextRadio;
    // End of variables declaration//GEN-END:variables
}
