/* -----------------------------------------------------------------------------
                       INSTITUTO TECNOLOGICO DE LA LAGUNA
                     INGENIERIA EN SISTEMAS COMPUTACIONALES
                       TOPICOS AVANZADOS DE PROGRAMACION "B"

                   SEMESTRE: ENE-JUN/2020   HORA: 10-11 HRS

 Clase jFrame donde el usuario visualiza la app e introduce los datos que desea convertir


  Archivo     : ConversionesApp
  Autor       : jesus Adrian Lopez Luevanos 18131253
  Fecha       : 11/10/2020
  Compilador  : Java j2SE V1.8.0
  Descripción : Aplicaion visual utilizando Java Swing que muestra un IU
                donde el usuario ingresa los datos que desea convertir de: 
                       °C a oF
                       °F a oC
                        Yardas a metros
                        Metros a yardas
                        Libras a kilos
                        Kilos a libras
                        Decimal a binario
                        Binario a decimal

--------------------------------------------------------------------------------
Ultima Modificacion: 
Fecha: 12/10/20
Modifico: Jesus Adrian Lopez Luevanos
Motivo: Añadio el boton ayuda 
*/
package app.Conversiones;

import mx.tecnm.itl.calculos.Conversiones;
import javax.swing.JOptionPane;

/**
 *
 * @author adria
 */
public class ConversionesFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConversionesFrame
     */
    public ConversionesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextDatos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabResultados = new javax.swing.JLabel();
        jComboConversion = new javax.swing.JComboBox<>();
        jButCalcular = new javax.swing.JButton();
        jButRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTextDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 0, 14))); // NOI18N

        jLabResultados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jComboConversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°F a °C", "°C a °F", "Yds a Mts", "Mts a Yds", "Kg a Lb", "Lb a Kg", "Decimal a Binario", "Binario a Decimal" }));

        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButRegresar.setText("Regresar");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButRegresar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(77, Short.MAX_VALUE)
                        .addComponent(jComboConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButCalcular)
                        .addGap(52, 52, 52)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboConversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButCalcular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButRegresar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed

       double Datos;
       long   n = 0;
       
       String conversion = this.jComboConversion.getSelectedItem().toString();
       
        try {

            Datos = Double.parseDouble ( this.jTextDatos.getText () );

        } catch ( NumberFormatException ex ) {
            JOptionPane.showMessageDialog ( this ,
                "El valor ingresado no es valido \n"
                    + "Por Favor ingrese uno correctamente" ,
                "Error #001" ,
                JOptionPane.ERROR_MESSAGE
            );
            this.jTextDatos.requestFocus ();
            return;
        }
        
          try {
            if ( conversion.equals ( "Decimal a Binario" ) )

            n = Integer.parseInt( this.jTextDatos.getText() );

        } catch ( NumberFormatException ex ) {
            JOptionPane.showMessageDialog ( this ,
                "El valor que ingreso es incorrecto \n"
                        + "Intente con un número entero" ,
                "Error #002" ,
                JOptionPane.ERROR_MESSAGE
            );
            this.jTextDatos.requestFocus ();
            return;
        }
          
        if ( conversion.equals         ( "°C a °F" ) )           {
            this.jLabResultados.setText ( Conversiones.Celsius_Farenheit ( Datos ) + "" );
            
        }  else if  ( conversion.equals  ( "°F a °C" ) )           {
            this.jLabResultados.setText ( Conversiones.Farenheit_Celsius ( Datos ) + "" );
             
        }   else if ( conversion.equals  ( "Yds a Mts") )    {
            this.jLabResultados.setText ( Conversiones.Yardas_Metros ( Datos ) + ""  );
            
        }  else if  ( conversion.equals  ( "Mts a Yds" )  )  {
            this.jLabResultados.setText ( Conversiones.Metros_Yardas ( Datos ) + "" );
            
        }  else if  ( conversion.equals  ( "Lb a Kg" ) )    {
            this.jLabResultados.setText ( Conversiones.Lb_kg ( Datos ) + "" );
            
        }  else if  ( conversion.equals  ( "Kg a Lb"  ) )   {
            this.jLabResultados.setText ( Conversiones.Kg_Lb ( Datos ) + "" );
            
        }  else if  ( conversion.equals  ( "Decimal a Binario" ) ) {
            this.jLabResultados.setText ( Conversiones.Decimal_Binario ( n ) + "" );
            
        }  else if  ( conversion.equals  ( "Binario a Decimal" ) ) {
           this.jLabResultados.setText ( Conversiones.Binario_Decimal( "" ) + "" );
        } 
 
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_jButRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversionesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JComboBox<String> jComboConversion;
    private javax.swing.JLabel jLabResultados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextDatos;
    // End of variables declaration//GEN-END:variables
}
