/* -----------------------------------------------------------------------------
                       INSTITUTO TECNOLOGICO DE LA LAGUNA
                     INGENIERIA EN SISTEMAS COMPUTACIONALES
                       TOPICOS AVANZADOS DE PROGRAMACION "B"

                   SEMESTRE: ENE-JUN/2013    HORA: 10-11 HRS

         Aplicación visual para calcular las operaciones matematicas.


  Archivo     : U1MatematicaApp
  Autor       : jesus Adrian Lopez Luevanos 18131253
  Fecha       : 30/09/2020
  Compilador  : Java j2SE V1.8.0
  Descripción : Aplicacion visual usando java swing que presenta un UI 
                donde el usuario puede seleccionar la operacion matematica que desea
                (factorial, permutacion, combinacion) para luego proceder capturar
                los datos y calcular el resultado.

--------------------------------------------------------------------------------
Ultima Modificacion:
Fecha: 02/10/2020
Modifico: Jesus Adrian Lopez Luevanos 18131253
Motivo: Se añadio el boton 'formula general' que tiene como finalidad abrir otro 
        JFrame donde se podra hacer la consulta de la funcion matematica Formula General.
*/

package Matematica;

import javax.swing.JOptionPane;

/**
 *
 * @author adria
 */
public class MatemanticaFrame extends javax.swing.JFrame {

    /**
     * Creates new form MatemanticaFrame
     */
    public MatemanticaFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jText_n = new javax.swing.JTextField();
        jLab_ValorX = new javax.swing.JLabel();
        jText_x = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabResultado = new javax.swing.JLabel();
        jButAyuda = new javax.swing.JButton();
        jBut_Calcular = new javax.swing.JButton();
        jComboOperaciones = new javax.swing.JComboBox<>();
        jBut_FG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MatematicaApp");

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        jLabel1.setText("Operación: ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel2.setText("n:");

        jLab_ValorX.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLab_ValorX.setText("x:");
        jLab_ValorX.setEnabled(false);
        jLab_ValorX.setOpaque(true);

        jText_x.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_n, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLab_ValorX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_x)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jText_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLab_ValorX)
                    .addComponent(jText_x, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jLabResultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jButAyuda.setText("?");
        jButAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAyudaActionPerformed(evt);
            }
        });

        jBut_Calcular.setText("Calcular");
        jBut_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_CalcularActionPerformed(evt);
            }
        });

        jComboOperaciones.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jComboOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Factorial", "Permutaciones", "Combinaciones", " " }));
        jComboOperaciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboOperacionesItemStateChanged(evt);
            }
        });

        jBut_FG.setText("Formula General");
        jBut_FG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_FGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButAyuda)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBut_FG))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBut_Calcular)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBut_FG))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jBut_Calcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButAyuda)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_CalcularActionPerformed

        int n = 0, x = 0;
        String Operacion = jComboOperaciones.getSelectedItem().toString();
        
       try{
           n = Integer.parseInt ( jText_n.getText() );  
       } catch ( NumberFormatException ex ){
           System.out.println( "El valor n debe de ser entero!!" );
           JOptionPane.showMessageDialog ( this, " Valor n debe de ser entero ;)",
                   "ERROR", 
                   JOptionPane.ERROR_MESSAGE  );
           return;
       }
       
       try{
           if ( Operacion.equals ( "Permutaciones" ) || 
                Operacion.equals ( "Combinaciones" ) ) 
                
               x = Integer.parseInt( jText_x.getText () );
           
       }catch ( NumberFormatException ex ){
           System.out.println( "El valor de x debe de ser entero" );
           JOptionPane.showMessageDialog ( this, " Valor x debe de ser entero ;)",
                   "ERROR", 
                   JOptionPane.ERROR_MESSAGE  );
           return;
           
       }
       
       if ( Operacion.equals ( "°F" ) ) { 
            jLabResultado.setText ( Matematica.Factorial( n ) + "" ) ;
           
       }else if ( Operacion.equals ( "Permutaciones" ) ){
            jLabResultado.setText( Matematica.Permutaciones( n , x ) + "") ;
           
       } else if (Operacion.equals( "Combinaciones" ) ){
            jLabResultado.setText( Matematica.Combinaciones( n, x ) + "" ) ;
       }
    }//GEN-LAST:event_jBut_CalcularActionPerformed

    private void jComboOperacionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboOperacionesItemStateChanged
        
        if ( jComboOperaciones.getSelectedItem().toString().equals ( "Factorial" ) ) {
            jLab_ValorX.setEnabled( false );
            jText_x.setEnabled( false );
        } else{
            jLab_ValorX.setEnabled( true );
            jText_x.setEnabled( true );
        }
    }//GEN-LAST:event_jComboOperacionesItemStateChanged

    private void jButAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAyudaActionPerformed
        JOptionPane.showMessageDialog ( this, 
                "Tecnologico Nacional de México \n"
                        + "Instituto Tecnologico de la Laguna \n"
                        + "ISC Topicos Avanzados de programación \n\n"
                        + "MatematicaApp v 1.0 \n\n"
                        + "Desarrollado por \n"
                        + "Jesus Adrian Lopez Luevanos \n\n"
                        + "(C)Derechos Reservados 2020 \n",
                          "Acerca de",
                JOptionPane.INFORMATION_MESSAGE
        );
        
    }//GEN-LAST:event_jButAyudaActionPerformed

    private void jBut_FGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_FGActionPerformed
      FormulaGeneral FG = new FormulaGeneral(this);
      FG.setVisible(true);
      this.setVisible(false);
        
    }//GEN-LAST:event_jBut_FGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatemanticaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatemanticaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatemanticaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatemanticaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatemanticaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAyuda;
    private javax.swing.JButton jBut_Calcular;
    private javax.swing.JButton jBut_FG;
    private javax.swing.JComboBox<String> jComboOperaciones;
    private javax.swing.JLabel jLabResultado;
    private javax.swing.JLabel jLab_ValorX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jText_n;
    private javax.swing.JTextField jText_x;
    // End of variables declaration//GEN-END:variables
}
